import fs from 'fs';
import 'dotenv/config';

const API_URL = 'http://localhost:5000/api';

async function runTestFlow() {
  console.log('\n--- 🚀 Starting 100-Page PFE Rapport Generation Test ---');
  
  if (!process.env.ANTHROPIC_API_KEY) {
    console.log('\n⚠️ WARNING: You do not have ANTHROPIC_API_KEY set in your .env file!');
    console.log('The system will return a mock JSON response to prevent crashing.');
    console.log('To get the REAL 100-page text, please add your Claude API key to backend/.env!\n');
  }

  // 1. Register User (or Login if already exists)
  console.log('1. 👤 Authenticating...');
  let res = await fetch(`${API_URL}/auth/register`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      name: "Tarek Mansouri", email: "tarek100@student.com", password: "password123", role: "student"
    })
  });
  if (res.status === 400) {
    res = await fetch(`${API_URL}/auth/login`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email: "tarek100@student.com", password: "password123" })
    });
  }
  let cookie = res.headers.get('set-cookie');
  if (!cookie) throw new Error("Failed to authenticate user");
  console.log('✅ Authenticated!');

  // 2. Create Rapport
  console.log('\n2. 📄 Creating empty Draft Rapport...');
  res = await fetch(`${API_URL}/rapports`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Cookie': cookie },
    body: JSON.stringify({ templateId: null })
  });
  const rapport = await res.json();
  const rapportId = rapport._id;
  console.log(`✅ Rapport created! ID: ${rapportId}`);

  // 3. Save ALL custom 100-page Wizard Answers
  console.log('\n3. 💾 Simulating user typing answers into the Wizard forms...');
  const wizardAnswers = {
    templateName: "Template B",
    studentName: "Tarek Mansouri",
    university: "INSAT",
    department: "Génie Logiciel",
    degree: "Ingénieur en Informatique",
    academicYear: "2023-2024",
    supervisor: "Dr. Foulen Ben Foulen",
    companyName: "Viamobile Tunisie",
    sector: "Fintech",
    companySize: "150 employés",
    companyLocation: "Les Berges du Lac, Tunis",
    role: "Ingénieur Stagiaire Fullstack",
    internshipDuration: "6 mois",
    companyDepartment: "Mobile & Web",
    mentor: "Ahmed Tech Lead",
    companyPresentation: "Viamobile est un leader fintech en Tunisie.",
    projectTitle: "SuperApp Bancaire",
    problem: "L'ancienne application était très lente.",
    objective: "Refonte totale de la SuperApp Bancaire avec Flutter et Node.js.",
    technologies: ["Node.js", "Flutter", "MongoDB", "Redis"],
    methodology: "Agile Scrum",
    competingSolutions: ["D17", "Flouci", "SobFlous"],
    actors: [
        { name: "Client", role: "Paiement et transfert" },
        { name: "Admin", role: "Gestion des utilisateurs" }
    ],
    sprints: [
        { name: "Sprint 1: Auth", dateRange: "Janvier" },
        { name: "Sprint 2: Paiement", dateRange: "Février" },
        { name: "Sprint 3: QR Code", dateRange: "Mars" },
        { name: "Sprint 4: Tests", dateRange: "Avril" }
    ],
    perspectives: "Intégration de paiements internationaux."
  };
  
  res = await fetch(`${API_URL}/rapports/${rapportId}/autosave`, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', 'Cookie': cookie },
    body: JSON.stringify({ currentStep: 9, wizardAnswers, stepCompletion: [100, 100, 100, 100, 100, 100, 100, 100, 100] })
  });
  console.log(`✅ Answers saved directly to MongoDB!`);

  // 4. Trigger Claude AI Full Generation
  console.log('\n4. 🧠 TRIGGERING CLAUDE AI: Generating Full JSON Content (This takes 1-2 mins if API key is active)...');
  res = await fetch(`${API_URL}/ai/generate-full/${rapportId}`, {
    method: 'POST',
    headers: { 'Cookie': cookie }
  });
  
  const aiResult = await res.json();
  if (!res.ok) {
     console.error("❌ AI Generation Failed:", aiResult);
     return;
  }
  
  // 5. Save the huge JSON output to disk
  console.log('\n5. 📝 Saving the massive JSON response to your computer...');
  fs.writeFileSync(`full_100_page_rapport_${rapportId}.json`, JSON.stringify(aiResult.content, null, 2));
  
  console.log(`🎉 Success! File saved as full_100_page_rapport_${rapportId}.json`);
  console.log('\nOpen this JSON file to view the massive Tunisian structure generated by the AI!');
  console.log('NOTE: Converting this vast JSON structure back into a DOCX/PDF requires building the Frontend React Schema Renderer next!');
}

runTestFlow().catch(console.error);
